# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'

  # Pods for GithubApp
  target 'GithubAppTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
  end

end
